#!/bin/sh
# /usr/lib/sa/sa1.sh
# (C) 1999-2006 Sebastien Godard (sysstat <at> wanadoo.fr)
#
umask 0027
<% if architecture == "i386" %>ENDIR=/usr/lib/sa<% end %>
<% if architecture == "x86_64" %>ENDIR=/usr/lib64/sa<% end %>
cd ${ENDIR}
if [ $# = 0 ]
then
# Note: Stats are written at the end of previous file *and* at the
# beginning of the new one (when there is a file rotation) only if
# outfile has been specified as '-' on the command line...
	exec ${ENDIR}/sadc -F -L 1 1 -
else
	exec ${ENDIR}/sadc -F -L $* -
fi

