#!/bin/sh
#
# chkconfig: 235 03 97
# description: sysstat utilities for \
#              system monitoring.
#
# sysstat      Reset the system activity logs
#
# chkconfig: 12345 01 99
# description: Reset the system activity logs
# Author: Klaus.Franken@fth2.siemens.de
# Die Okt 12 10:05:41 EDT 1999
#
# Modified by:
# 1999/11/07 - Sebastien Godard <sebastien.godard@wanadoo.fr>
#	Now use '-d' option when starting sar.
# 2000/01/22 - Sebastien Godard <sebastien.godard@wanadoo.fr>
#	Rewritten from scratch. Call sadc instead of sar.
# 2004/01/22 - Nils Philippsen <nphilipp@redhat.com>
#   Adapt for chkconfig. Call only once after booting.
# 2004/10/10 - Sebastien Godard (sysstat <at> wanadoo.fr)
#	Now returns real exit code.
# 2006/07/05 - Sebastien Godard (sysstat <at> wanadoo.fr)
#	Added support for chkconfig
#
# /etc/init.d/sysstat
#
umask 027
RETVAL=0
# Remove flag indicating that sadc was successfully launched
rm -f /tmp/sysstat.run

# See how we were called.
case "$1" in
  start)
        echo -n "Calling the system activity data collector (sadc): "
<% if architecture == "i386" %>/usr/lib/sa/sadc -F -L - && touch /tmp/sysstat.run<% end %>
<% if architecture == "x86_64" %>/usr/lib64/sa/sadc -F -L - && touch /tmp/sysstat.run<% end %>

# Try to guess if sadc was successfully launched. The difficulty
# here is that the exit code is lost when the above command is
# run via "su foo -c ..."
	if [ ! -f /tmp/sysstat.run ]; then
		RETVAL=1
	else
		rm -f /tmp/sysstat.run
	fi
        echo
        ;;
  stop|status|restart|reload)
        ;;
  *)
        echo "Usage: sysstat {start|stop|status|restart|reload}"
        exit 1
esac
exit ${RETVAL}

